# 5.16 List 2 Dimensi

In [1]:
#Latihan 1 List 2 Dimensi
matrix = [
    #Awali List dengan [ yang mengartikan bentuk program ini adalah list
    #Nama dari list adalah bebas
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12,13,14],
    [15,16,17,18,19,20]
]
#Jangan lupa akhiri dengan ] yang menandakan list ditutup
print(matrix)
#Print(matrix) berfungsi untuk mendapatkan output dari list yang sudah kita tulis di dalam tanda []

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12, 13, 14], [15, 16, 17, 18, 19, 20]]


In [2]:
#Latihan 2 List 2 Dimensi
for i in matrix:
    print(i)
    #variabel i dipakai untuk menyimpan isi dari element yang saat ini sedang diproses.
    #Nama variabel i sendiri boleh bebas, fungsinya hanya sebagai variabel bantu saja

#Dalam format ini, kita mendefinisikan variabel matrix sebagai sebuah array atau himpunan (salah satu dari tipe data string, list, tuple, set atau dictionary).
#Perulangan for akan dijalankan sebanyak jumlah elemen yang ada di dalam variabel matrix.

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20]


In [3]:
#Latihan 3 List 2 Dimensi
for baris in matrix:
    print(baris)
    #Disini dibuktikan bahwa i tidak selalu harus diberi nama i, contohnya bisa saja "baris"
    
    for j in baris:
        print(j)
        #Program ini adalah proses kedua dari for
        #Data yang sudah diurutkan menjadi 
        #[1,2,3,4]
        #[5,6,7,8]
        #[9, 10, 11, 12, 13, 14]
        #[15, 16, 17, 18, 19, 20]
        #Diurutkan lagi menjadi 
        #1
        #2
        #3
        #4, dst
        
#Program ini memuat 2 kali proses sehingga menyebabkan anggota list 'matrix' menjadi terurai

[1, 2, 3, 4]
1
2
3
4
[5, 6, 7, 8]
5
6
7
8
[9, 10, 11, 12, 13, 14]
9
10
11
12
13
14
[15, 16, 17, 18, 19, 20]
15
16
17
18
19
20


# 5.17 Tuples

In [4]:
angka = (0,1,1,3,4,5)

#List berikutnya diberi nama angka yang anggotanya adalah 0,1,1,3,4,5
#Tuples adalah urutan objek Python yang tidak berubah. 
#Tuples adalah urutan, seperti daftar. 
#Perbedaan utama antara Tuples dan daftarnya adalah bahwa tuples tidak dapat diubah tidak seperti List Python. 
#Tuples menggunakan tanda kurung, sedangkan List Python menggunakan tanda kurung siku.

In [5]:
#Latihan 1 Tuples

print(angka[0])
#Kode ini memerintahkan untuk mencetak elemen pertama dari list

#Kode ini merupakan untuk menampilkan elemen/anggota dari list 
#0 = elemen ke 0
#1 = elemen ke 1
#1 = elemen ke 2
#3 = elemen ke 3
#4 = elemen ke 4
#5 = elemen ke 5

#Sehingga hasil dari program ini adalah 0

0


In [6]:
#Latihan 2 Tuples

print(angka[5])
#Kode ini memerintahkan untuk mencetak elemen ke 5 yaitu adalah 5

5


In [7]:
#Latihan 3 Tuples

print(angka[0:3])
#[0:3] merupakan perintah untuk mencetak dari elemen pertama sampai elemen ke 2 dan elemen ke 3 tidak dicetak 
#Alhasil, cetakan dari kode ini adalah (0,1,1)
# 0 sebagai elemen ke 0
# 1 sebagai elemen ke 1
# 1 sebagai elemen ke 2

(0, 1, 1)


In [8]:
#Latihan 4 Tuples

for isi in angka[0:3]:
    print(isi)
    
    #Perintah for pada program ini berfungsi sama dengan perintah for pada list 2 dimensi
    #Hasil dari program ini adalah (0,1,1) akan diuraikan ke bawah

0
1
1


In [9]:
#Latihan 5 Tuples

angka[0] = 10

#Program ini tidak bisa menjalankan perintah karena tuples tidak bisa direplace
#Kita menggunakan Tuples apabila kita memiliki data yang tidak inggin dirubah, jika ingin dirubah menggunakan list

TypeError: 'tuple' object does not support item assignment

In [10]:
#Latihan 6 Tuples

angka.append(10)

#Append sebenarnya berfungsi untuk menambahkan anggota terakhir pada sebuah list
#Mengingat ini bukanlah list melainkan Tuples, maka 'append' tidak bisa bekerja pada program ini

AttributeError: 'tuple' object has no attribute 'append'

In [11]:
#Latihan 7 Tuples

angka.remove(5)

#Remove pada program ini sebenarnya berfungsi untuk menghapus elemen '5' pada sebuah list
#Namun, karena program ini merupakan Tuples, maka perintah remove tidak bisa dijalankan 

AttributeError: 'tuple' object has no attribute 'remove'

In [ ]:
#Latihan 8 Tuples

angka.count(1)

#Count pada program ini berfungsi untuk menghitung jumlah angka 1 pada tuples 'angka'
#Hanya ada 2 angka 1 pada Tuples 'angka', sehingga 1+1 = 2
#Maka hasil dari program ini adalah 2

In [ ]:
#Latihan 9 Tuples

angka.index(3)

#Fungsi index pada program ini adalah untuk mengetahui posisi elemen, pada kasus ini adalah elemen 3
#Elemen angka 3 terletak pada urutan ke 3 dalam list 'angka'
#Jadi hasil dari program ini adalah 3

In [ ]:
#Latihan 10 Tuples

tup1 = (50,) 
print(tup1[0])

#Jika elemen tuple hanya ada 1 elemen saja, tetap harus menuliskan ',' karena jika tidak program akan error

In [ ]:
#Latihan 11 Tuples
#Update Nilai Dalam Tuple Python

tup1 = (12, 34.56)
tup2 = ('abc', 'xyz')
tup3 = tup1 + tup2
print (tup3)

#Karena elemen pada tuples tidak bisa ditambahkan, maka kita bisa siasati dengan menggabungkan antara elemen 1 dan elemen 2 
#Kemudian kita mencetak elemen baru yang merupakangabungan dari 2 elemen sebelumnya 

# 5.18 Dictionaries

In [12]:
data_orang = {
    'nama': 'Ni Luh Gede Rika Bisathania',
    'umur' : 19,
    'apakah_singel' : False
}

#Dictionaries digunakan jika datanya terkait satu sama lain
#Karena kumpulan nilai di dictionary menggunakan key dan value, maka setiap key dipisahkan dari value-nya dengan tanda titik dua ":"  
#setiap nilai dipisahkan tanda koma , dan di bungkus menggunakan tanda kurung kurawal {}.
#Untuk nilai dari value bisa di isi dengan tipe data apapun (string, list, boolean, dictionary, dll),
#Sedangkan untuk key harus berupa tipe data yang tidak berubah seperti string atau number.

In [13]:
#latihan 1 Dictionaries

print(data_orang['nama'])

#Pada program ini kita memanggil definisi dari 'nama' pada dictionaries data_orang
#'nama' didefinisikan dengan 'Ni Luh Gede Rika Bisathania'
#Sehingga hasilnya adalah Ni Luh Gede Rika Bisathania

Ni Luh Gede Rika Bisathania


In [14]:
#latihan 2 Dictionaries

print(data_orang.get('nama'))

#Program ini sebenarnya berfungsi sama seperti Latihan 1, namun yang membedakan adalah penggunaan 'get'
#Kalau menggunakan get pakai (), sedangkan kalau tidak pakai menggunakan []

Ni Luh Gede Rika Bisathania


In [15]:
#latihan 3 Dictionaries

print(data_orang.get('Nama'))

#Perintah get tidak menemukan 'Nama' karena yang digunakan adalah 'nama'
#Sehingga komputer tidak menemukan definisi dari 'Nama' dan mengeluarkan hasil 'None'

None


In [16]:
#latihan 4 Dictionaries

print(data_orang.get('tanggal_lahir'))

#Tanggal lahir tidak ditemukan karena memang tidak dicantumkan 

None


In [17]:
#latihan 5 Dictionaries

print(data_orang['tanggal_lahir'])

#Jika kita menggunakan kurung siku [], apabila definisi tidak ditemukan, dia tidak akan mengeluarkan hasil 'None', melainkan error

KeyError: 'tanggal_lahir'

In [18]:
#latihan 6 Dictionaries

print(data_orang.get('tanggal_lahir', '29 Februari 2004'))

#Program ini adalah untuk menambahkan data yang tidak didefinisikan
#Pada Latihan 4 Dictionaris, 'tanggal_lahir' menghasilkan output 'None'
#Namun, setelah ditambahkan '29 Februari 2004' pada perintah get, dia akan menghasilkan 29 Februari 2004
#Perintah ini tidak permanen.
#Jika ingin perintah menjadi permanen, bisa menambahkan definisi 'tanggal_lahir' pada data_orang yang paling awal

29 Februari 2004


In [19]:
#latihan 7 Dictionaries

print(data_orang)

#Pada program ini dibuktikan bahwa 'tanggal_lahir' yang sudah ditambahkan pada latihan 6 Dictionaries tidak permanen
#Buktinya, jika kita print(data_orang) hanya akan keluar definisi nama, umur, dan apakah singel

{'nama': 'Ni Luh Gede Rika Bisathania', 'umur': 19, 'apakah_singel': False}


In [20]:
#latihan 8 Dictionaries

data_orang['nomor_HP'] = '089634821414'

#Memasukkan data baru pada 'data_orang'

In [21]:
#latihan 9 Dictionaries

print(data_orang['nomor_HP'])

#Cetak 'nomor_HP', maka definisinya akan tercetak

089634821414


In [28]:
#latihan 10 Dictionaries

print(data_orang)

#Dengan menggunakan program seperti ini, data akan berubah secara permanen
#Sekarang, 'data_orang' akan berisi nama, umur, apakah_singel, dan nomor_HP

{'nama': 'Ni Luh Gede Rika Bisathania', 'umur': 19, 'apakah_singel': False, 'nomor_HP': '089634821414'}


In [37]:
#latihan 11 Dictionaries

buku = {
    'Judul' : 'Ayo Belajar Algoritma',
    'Penulis' : 'Rika Bisathania',
    'Tanggal Terbit' : '31 Maret 2030',
    'Penerbit' : 'Surya Pustaka',
    'Target Pasar' : 'Pelajar'
    #Saat memasukkan data, ingat untuk memberikan koma(,) pada akhir kalimat, kecuali data terakhir
}

for key in buku:
  print(key, '->', buku[key])

#Kita juga bisa menampilkan semua isi dari sebuah dictionary dengan memanfaatkan perulangan.

Judul -> Ayo Belajar Algoritma
Penulis -> Rika Bisathania
Tanggal Terbit -> 31 Maret 2030
Penerbit -> Surya Pustaka
Target Pasar -> Pelajar


In [38]:
#latihan 12 Dictionaries

for nama_atribut, nilai in buku.items():
  print(nama_atribut, '->', nilai)

#Atau kita juga bisa memanggil fungsi dictionary.items() untuk perulangan yang lebih simpel
#Definisikan data dari 'buku' dengan nama 'nama_atribut'

Judul -> Ayo Belajar Algoritma
Penulis -> Rika Bisathania
Tanggal Terbit -> 31 Maret 2030
Penerbit -> Surya Pustaka
Target Pasar -> Pelajar


In [24]:
#Membuat program untuk merubah nomor HP yang tadinya berupa angka menjadi sebutan bilangan tersebut

angka = {
    '0' : 'nol',
    '1' : 'satu',
    '2' : 'dua',
    '3' : 'tiga',
    '4' : 'empat',
    '5' : 'lima',
    '6' : 'enam',
    '7' : 'tujuh',
    '8' : 'delapan',
    '9' : 'sembilan'
}

#Kita definisikan terlebih dahulu semua angka menjadi huruf

In [25]:
#latihan 13 Dictionaries

nomor_HP = input('Masukkan nomor HP anda')
nomor_angka = ''
for isi in nomor_HP :
    nomor_angka += angka.get(isi) + ' '
print(nomor_angka)

Masukkan nomor HP anda0123
nol satu dua tiga 


# 5.19 Fungsi dalam Python

In [ ]:
#Fungsi pada python adalah kumpulan perintah atau baris kode yang dikelompokkan menjadi satu kesatuan untuk kemudian bisa dipanggil atau digunakan berkali-kali.
#Sebuah fungsi bisa menerima parameter, bisa mengembalikan suatu nilai, dan bisa dipanggil berkali-kali secara independen.
#Dengan fungsi kita bisa memecah program besar yang kita tulis, menjadi bagian-bagian kecil dengan tugasnya masing-masing.

In [45]:
#Latihan 1 Fungsi dalam Python
#Parameter wajib diisi

def full_name(first_name,last_name):
#Kata kunci "def" yang menjadi pertanda bahwa blok kode program adalah sebuah fungsi
    print(f"Nama lengkapnya adalah {first_name} {last_name}")
    
#Parameter di dalam python bisa lebih dari satu, bisa wajib semua (harus diisi), dan bisa juga bersifat opsional.
#Namun, pada kasus ini parameter bersifat wajib semua, jika tidak diisi salah satu maka akan mendapatkan error

In [47]:
first_name = input('Nama depan anda adalah :')
last_name = input ('Nama belakang anda adalah :')
full_name(first_name, last_name)

#Dengan program seperti ini, kita sudah memanfaatkan fungsi dan parameter pada python.

Nama depan anda adalah :Rika
Nama belakang anda adalah :Bisathania
Nama lengkapnya adalah Rika Bisathania


In [50]:
#Latihan 2 Fungsi dalam Python
#Parameter tidak wajib diisi

def suhu_udara (daerah, derajat, satuan = 'celcius'):
  print(f"Suhu di {daerah} adalah {derajat} {satuan}")
#Pada definisi ini, kita mendefinisikan 3 buah parameter, yaitu :
#'daerah'
#'derajat'
# suhu = 'celcius'
#Dua parameter pertama adalah bersifat wajib dan harus diisi, sedangkan parameter ketiga tidak wajib. Jika tidak kita isi, maka nilai default-nya adalah “celcius”.

suhu_udara("Bali", 30)
suhu_udara("Yogyakarta", 86, 'Fahrenheit')

Suhu di Bali adalah 30 celcius
Suhu di Yogyakarta adalah 86 Fahrenheit


# 5.19.1Tugas Fungsi pada Python 

In [51]:
# dua jenis tugas fungsi pada python yaitu menjalankan perintah dan menampilkan hasil perhitungan 

In [52]:
#Latihan 1 Tugas Fungsi pada Python

def waktu_sampai(jarak,kecepatan):
#Gunakan def sebagai kode bahwa program ini sebuah fungsi 
#Waktu dapat dihitung dengan komponen jarak dan kecepatan 
    waktu = jarak/kecepatan
    #waktu dapat dihitung dengan jarak dibagi dengan kecepatan
    print(waktu)

In [53]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu
    #disini kita menggunakan return karena ingin mengembalikan nilai yang tersimpan dalam sebuah variabel kepada kode yang akan memanggil function tersebut.
    #Keyword return berfungsi untuk mengembalikan suatu data, sedangkan fungsi print untuk mencetak teks di terminal.

In [54]:
waktu_sampai(80,60)
#Untuk menghitung waktu_sampai, kita tinggal memasukkan angka yang kita inginkan pada tanda kurung
#(80,60) artinya : 80 untuk jarak dan 60 untuk kecepatan 
#Kemudian komputer akan memproses pembagian dari 2 data tersebut dan mendapatkan hasil 1.3333333333333333

1.3333333333333333


In [55]:
waktu_tempuh(80,60)

#sama seperti rumus untuk menghitung waktu_sampai
#(80,60) artinya : 80 untuk jarak dan 60 untuk kecepatan

1.3333333333333333

In [56]:
a = waktu_sampai(80,60)
#Kita definisikan a sebagai waktu sampai dengan jaraknya adalah 80 dan 60 sebagai kecepatannya
#Boleh didefinisikan dengan nama selain a
print(a)
#Setelah hasilnya diproses, tentunya kita harus menggunakan perintah print untuk mencetak hasil dari waktu_sampai

1.3333333333333333
None


In [57]:
b = waktu_tempuh(80,60)
#Kita mendefinisikan a sebagai waktu sampai dengan jaraknya adalah 80 dan kecepatannya adalah 60
#Boleh didefinisikan dengan nama selain b
print(b)
#Gunakan perintah print untuk mencetak hasilnya

1.3333333333333333


In [4]:
#Latihan 2 Tugas Fungsi pada Python

import numpy as np
#Gunakan numpy pada saat menghitung luas_lingkaran
#Numpy menyediakan fungsi yang siap pakai untuk memudahkan dalam melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.

def luas_segitiga(alas,tinggi):
#Komponen dari luas_segitiga adalah alas dan tinggi, masukkan komponen tersebut
    luas = (1/2)*alas*tinggi
    #Masukkan rumus dari luas segitiga
    return luas
    #Gunakan retun untuk mengembalikan nilai yang tersimpan dalam sebuah variabel kepada kode yang akan memanggil function tersebut
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari**2)
    #Karena kita sudah mendefinisikan numpy menjadi np, maka cukup menuliskan np saja
    #Jika Anda sudah menggunakan numpy, lebih baik menggunakan konstanta numpy saja yaitu (pi)
    return luas
def luas_persegi(sisi):
#Komponen dari luas persegi hanyalah sisi
    luas = sisi**2
    #Masukkan rumus untuk menghitung luas_persegi yaitu sisixsisi atau dituliskan sisi**2(sisi pangkat 2)
    return luas
def luas_persegi_panjang(panjang,lebar):
#Masukkan komponen dari luas_persegi_panjang yaitu panjang dan lebar
    luas = panjang*lebar
    #Masukkan rumus dari luas persegi panjang yaitu panjang x lebar
    return luas

In [2]:
luas_segitiga(30,15)
#Untuk menghitung luas segitiga, tuliskan luas_segitiga sesuai dengan definisi 
#(30,15) artinya : 30 untuk alas, dana 15 untuk tinggi
#Kemudian angka tersebut diproses sesuai dengan definisi luas_segitiga yang telah kita tuliskan

225.0

In [5]:
luas_lingkaran(5)
#Kita hanya memasukkan 1 komponen saja yaitu jari" saja
#5 adalah untuk jari_jari

78.53981633974483

In [6]:
luas_persegi(10)
#Sama seperti luas_segitiga kita hanya memerlukan 1 komponen saja yaitu sisi

100

In [7]:
luas_persegi_panjang(3,7)
#(7,3) artinya : 7 untuk panjang dan 3 untuk lebar
#Hasilnya adalah 21 karena kita mendefinisikan luasnya adalah panjang*lebar

21

In [3]:
#Latihan 3 Tugas Fungsi pada Python

import numpy as np
#Gunakan numpy pada saat menghitung luas_lingkaran
#Numpy menyediakan fungsi yang siap pakai untuk memudahkan dalam melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.
def luas_segitiga(alas,tinggi):
#Komponen dari luas_segitiga adalah alas dan tinggi, masukkan komponen tersebut
    luas = (1/2)*alas*tinggi
    #Masukkan rumus dari luas segitiga
    return luas
    #Gunakan retun untuk mengembalikan nilai yang tersimpan dalam sebuah variabel kepada kode yang akan memanggil function tersebut
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari**2)
    #Karena kita sudah mendefinisikan numpy menjadi np, maka cukup menuliskan np saja
    #Jika Anda sudah menggunakan numpy, lebih baik menggunakan konstanta numpy saja yaitu (pi)
    return luas
def luas_persegi(sisi):
#Komponen dari luas persegi hanyalah sisi
    luas = sisi**2
    #Masukkan rumus untuk menghitung luas_persegi yaitu sisixsisi atau dituliskan sisi**2(sisi pangkat 2)
    return luas
def luas_persegi_panjang(panjang,lebar):
#Masukkan komponen dari luas_persegi_panjang yaitu panjang dan lebar
    luas = panjang*lebar
    #Masukkan rumus dari luas persegi panjang yaitu panjang x lebar
    return luas

#Mengitung bidang menggunakan metode input
jenis_bidang = input('Tulis jenis bidangnya :')
#Program ini untuk mengimput jenis bidang yang akan diproses
if jenis_bidang.upper() == 'SEGITIGA':
#Program ini untuk merubah huruf yang diimput jika hurufnya huruf kecil menjadi huruf besar
    alas = float(input('Berapakah panjang alasnya ?'))
    #Gunakan float karena data yang diimput tidak selalu bilangan bulat, bisa saja desimal atau pecahan
    tinggi = float(input('Berapakah tingginya ?'))
    luas = luas_segitiga(alas,tinggi)
    #Kemudian kita masukkan elemen dari luas segitiga yaitu alas dan tinggi
    print(f"luas {jenis_bidang} adalah {luas}")
    #Pada bagian ini, pastikan untuk menggunakan kurung kurawa {}
elif jenis_bidang.upper() == 'LINGKARAN':
#Pengambilan keputusan (kondisi if elif) merupakan lanjutan/percabangan logika dari kondisi if
#Dengan elif kita bisa membuat kode program yang akan menyeleksi beberapa kemungkinan yang bisa terjadi.
#Hampir sama dengan kondisi “else”, bedanya kondisi “elif” bisa banyak dan tidak hanya satu.
    jari_jari = float(input('Berapakah panjang jari-jarinya ?'))
    luas = luas_lingkaran(jari_jari)
    print(f"luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI':
    sisi = float(input('Berapakah panjang sisinya?'))
    luas = luas_persegi(sisi)
    print(f"luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG' :
    panjang = float(input('Berapakah panjangnya?'))
    lebar = float(input('Berapakah lebarnya?'))
    print(f"luas{jenis_bidang} adalah {luas}")
else:
#kondisi terakhir dimana semua kondisi sebelumnya tidak ada yang terpenuhi.
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI, dan PERSEGI PANJANG.")
    print('Terimakasih')  
    #Apabila perintah tidak ada yang terpenuhi, maka akan keluar 3 kalimat ini

Tulis jenis bidangnyabalok
Maaf bidang balok yang anda masukkan tidak ada.
Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI, dan PERSEGI PANJANG.
Terimakasih


# 5.20 Numpy

## 5.20.1 Perintah Dasar pada Numpy

In [9]:
import numpy as np
#Pastikan untuk menuliskan perintah ini untuk memanggil library numpy
d = np.array([1,2,3,4])
print(d)
#Hasilnya sama seperti membuat list

[1 2 3 4]


In [10]:
import numpy as np
c = np.array([[5,6,7,8],[9,8,7,6],[7,8,9,6]])
print(c)
#Apabila kita membuat 2 atau lebih array, maka akan dicetak secara vertikal

[[5 6 7 8]
 [9 8 7 6]
 [7 8 9 6]]


In [11]:
d.ndim
#Fungsi ndim adalah untuk mengetahui jumlah dimensi array NumPy

1

In [12]:
c.ndim
#Dimensi pada c adalah 2

2

In [13]:
d.shape
#Pada fungsi shape menghasilkan sebuah tuple yang berisikan panjang sebuah array pada tiap dimensi.
#Array d memiliki shape 4, yaitu panjang array pada 1-dimensi array.

(4,)

In [14]:
c.shape
#Array c memiliki shape 3, yaitu panjang array pada 2-dimensi array.

(3, 4)

## 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [15]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
d[1,3]
#[1,3], 1 melambangkan indeks ke 2 dari 3 indeks yang tersedia, indeks pertama dihitung 0
#3 melambangkan elemen ke 4 dari indeks ke 2, karena dimulai dari 0 
#[1,2,3,4] = merupakan indeks ke 0
#[5,6,7,8] = merupakan indeks ke 1
    #5 = elemen ke 0
    #6 = elemen ke 1
    #7 = elemen ke 2
    #8 = elemen ke 3
#[9,10,11,12] = merupakan indeks ke 2

8

In [19]:
d[1,:]
#Kode ini memuat perintah untuk mencetak indeks ke 1
#[1,2,3,4] = merupakan indeks ke 0
#[5,6,7,8] = merupakan indeks ke 1
#[9,10,11,12] = merupakan indeks ke 2
#Karena tidak dituliskan elemen ke berapa dari indeks yang ingin dicetak, maka semua elemen dicetak

array([5, 6, 7, 8])

In [20]:
d[:,2]
#Kode ini memuat perintah untuk mencetak elemen ke 2 pada semua indeks

array([ 3,  7, 11])

In [21]:
d[0,1:3]
#Kode ini untuk mencetak indeks ke 0
#[1,3] artinya yaitu cetak elemen ke 1 sampai 2

array([2, 3])

In [22]:
d[0,0:3:2]

#Program ini untuk mencetak indeks ke 0
#Elemen dari indeks ke 0 ini dicetak dari elemen ke 0 sampai sebelum elemen ke 3 (1,2,3,4)
#Dengan loncatan sebanyak 2 kali

array([1, 3])

In [23]:
d[0,0] = 100
print(d)

#Program ini adalah untuk mengganti indeks ke 0 dan elemen ke 0 dengan angka 100

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## 5.20.3 Matrix pada Numpy

In [24]:
np.ones((2,3))
#Mencetak matrix 2x3 dengan elemennya adalah 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.zeros((2,3))
#Mencetak matrix 2x3 dengan elemennya adalah 0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.identity(5)
#Mencetak matrix identitas dengan ukuran 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.ones((5,3,4))
#Mencetak 5 buah matrix ukuran 3x4 dengan 1 sebagai semua elemennya

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [32]:
np.full((3,2),9)
#Untuk mencetak matrix berukuran 3x2 dengan 9 sebagai semua elemennya

array([[9, 9],
       [9, 9],
       [9, 9]])

In [33]:
np.random.rand(4,3)
#Untuk mencetak matrix berukuran 4x3 
#Metode rand() pada modul random mengembalikan float acak antara 0 dan 1.

array([[0.84347728, 0.56740035, 0.97052733],
       [0.8921451 , 0.06343574, 0.1715109 ],
       [0.16878125, 0.04845983, 0.43778399],
       [0.94088576, 0.57848325, 0.05909996]])

In [39]:
np.random.randint(1,10,size=(3,4))
#Mencetak matrix ukuran 3x4 dengan elemen-elemennya terdiri dari bilangan 1 sampai 10

array([[8, 4, 3, 9],
       [3, 1, 4, 3],
       [2, 1, 9, 1]])

## 5.20.4 Copy pada Numpy 

In [42]:
#Latihan 1 Copy pada Numpy

a= np.array([1,2,3,4,5])
print(a)

#Program ini adalah untuk mencetak anggota dari array a yaitu 1,2,3,4,5

[1 2 3 4 5]


In [43]:
b = a
print(b)

#Program ini adalah untuk membuat elemen dari array b adalah sama persis dengan array a

[1 2 3 4 5]


In [45]:
b[0] = 10
print(b)
#Program ini adalah untuk mengganti elemen ke 0 yang tadinya adalah angka 1 menjadi angka 10

[10  2  3  4  5]


In [46]:
print(a)
#Karena tadi kita sudah mengganti elemen ke 0 dengan 10, jadi elemen dari array a menjadi 10,2,3,4,5

[10  2  3  4  5]


In [47]:
#Latihan 2 Copy pada Numpy

c = np.array([1,2,3,4,5])
#Kita definisikan array c dengan elemennya adalah 1,2,3,4,5

In [49]:
d = c.copy()
print(d)

#Terdapat cara lain untuk mengcopy sebuah array supaya identik dengan array yang baru
#Contohnya adalah cara ini

[1 2 3 4 5]


In [52]:
d[0] = 1002
print(d)

#Karena kita mengganti elemen ke 0 pada array d, alhasil elemen dari array d menjadi 1002,2,3,4,5

[1002    2    3    4    5]


In [55]:
print(c)

#Karena kita tidak pernah merubah elemen dari array c, maka elemen-elemen dari array c tetap sama yaitu 1,2,3,4

[1 2 3 4 5]


## 5.20.5 Operasi Matematika pada Numpy

In [59]:
a = np.array([5,6,7,8,9])

#Kita definisikan array a dengan elemennya yaitu 5,6,7,8,9

In [61]:
a+2

#Program ini memerintahkan setiap elemen dari array a dijumlahkan 2, sehingga
#5+2 = 7
#6+2 = 8
#7+2 = 9
#8+2 = 10
#9+2 = 11

array([ 7,  8,  9, 10, 11])

In [63]:
a-10
#Program ini memerintahkan bahwa setiap elemen dari a harus dikurangi dengan 10

array([-5, -4, -3, -2, -1])

In [64]:
a*4
#Program ini memerintahkan bahwa setiap elemen dari a harus dikalikan dengan 4

array([20, 24, 28, 32, 36])

In [66]:
a/5
#Program ini untuk memuat perintah bahwa setiap elemen dari array a harus dibagi dengan 5

array([1. , 1.2, 1.4, 1.6, 1.8])

In [67]:
a**3
#Program ini adalah untuk memuat perintah bahwa setiap elemen dari array a harus dipangkatkan 3

array([125, 216, 343, 512, 729], dtype=int32)

In [70]:
b = np.array([6,7,8,9,10,11,12,13])
#Kita mempunyai array baru yaitu array b dengan elemennya adalah 6,7,8,9,10
#Baik nama array ataupun elemen array adalah bebas 

In [69]:
a+b
#Program ini adalah untuk menjumlahkan 2 buah elemen pada array yang berbeda
#Apabila jumlah elemen pada kedua array berbeda, maka hanya akan diproses yang mempunyai pasangan saja
#(5+6 , 6+7 , 7+8 , 8+9 , 9+10) sebenarnya masih ada sisa elemen pada array b, namun hanya diproses sejumlah array a

array([11, 13, 15, 17, 19])

In [71]:
a-b
#Namun pada operasi pengurangan, elemen array yang berbeda jumlah tidak dapat diproses

ValueError: operands could not be broadcast together with shapes (5,) (8,) 

In [78]:
a/b
#Operasi pembagian masih bisa dijalankan walaupun jumlah elemen array berbeda 

array([0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [79]:
b**a
#Operasi pangkat dapat diproses walaupun jumlah elemen array berbeda

array([      7776,     117649,    2097152,   43046721, 1000000000],
      dtype=int32)

In [74]:
a = np.array([5,6,7,8,9])
b = np.array([6,7,8,9,10])
#Untuk memproses operasi pengurangan, kita akan membuat array yang baru dengan jumlah elemen sama 

In [77]:
a-b
#Dengan seperti ini, operasi pengurangan dapat dilakukan 

array([-1, -1, -1, -1, -1])

In [75]:
a*b
#Operasi perkalian juga tidak dapat dijalankan apabila jumlah elemen berbeda

array([30, 42, 56, 72, 90])

In [83]:
np.cos(a)
#Program ini adalah untuk memberikan perintah mencetak cos dari semua elemen a

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [82]:
np.cos(b)
#Program ini adalah untuk memberikan perintah mencetak cos dari semua elemen b

array([ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [84]:
np.tan(a)
#Program ini adalah untuk memberikan perintah untuk mencetak tan dari semua elemen a

array([-3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [85]:
np.sinh(a)
#Fungsi ini akan mengembalikan sinus hiperbolik dari bilangan x yang diberikan.

array([  74.20321058,  201.71315737,  548.31612327, 1490.47882579,
       4051.54190208])

In [86]:
np.cosh(a)
#Ini akan mengembalikan cosinus hiperbolik dari angka yang diberikan x.

array([  74.20994852,  201.71563612,  548.31703516, 1490.47916125,
       4051.54202549])

In [87]:
np.tanh(a)
#Ini akan mengembalikan tangen hiperbolik dari angka yang diberikan x.

array([0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997])

In [88]:
np.sqrt(a)
#Ini akan mengembalikan akar kuadrat dari argumen yang diteruskan x.

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## 5.20.6 Perkalian Matrix pada Numpy

In [114]:
a = np.array ([[1,2,3,4],[5,6,7,8]])
print(a)

#Di dalam array a kita buat terdapat 2 indeks 

[[1 2 3 4]
 [5 6 7 8]]


In [119]:
b = np.array ([[9,8,7,6],[7,1,4,3]])
print(b)
#Begitupun pada array b kita akan membuat 2 buah indeks di dalamnya

[[9 8 7 6]
 [7 1 4 3]]


In [120]:
c = a*b
print(c)
#Unuk operasi perkalian, jumlah kedua indeks harus memiliki jumlah elemen yang sama, jika berbeda maka hasilnya akan error

[[ 9 16 21 24]
 [35  6 28 24]]


In [122]:
d = np.matmul(a,b)
print(d)

#Kode ini error karena a merupakan matrix 2x4  dan b juga merupakan matrix 2x4
#Matrix yang sama-sama berukuran 2x4 tidak dapat diproses karena tidak memenuhi persyaratan untuk perkalian matrix

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [123]:
e = np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)

#Kita akan membuat sebuah array baru yang bernama e dengan ukurannya adalah 4x2

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [124]:
f = np.matmul(a,e)
print(f)
#Matrix a yang berukuran 2x4 akan dikalikan dengan matrix b yang berukuran 4x2
#Karena memenuhi syarat perkalian matrix, kedua matrix ini dapat diproses

[[130 140]
 [322 348]]


In [125]:
g = a*e

#Matrix 2x4 dan 4x2 tidak bisa diproses karena jumlah baris dan kolomnya berbeda 
#Bentuk kode seperti ini bukan merupakan perkalian matrix

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

## 5.20.7 min, max, dan sum pada Numpy

In [134]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [135]:
b = np.min(a)
print(b)

#b didefinisikan sebagai nilai terkecil (minimal) dari semua angka yang ada dalam array a
#Angka terkecil dari array a adalah 1

1


In [136]:
c = np.min(a,axis=0)
print(c)

#Secara keseluruhan, program ini adalah untuk menemukan nilai minimun dalam matrix pada baris tertentu
#Axis = 0 menujukan 'baris' data array

[1 2 3 4]


In [140]:
d = np.min(a,axis=1)
print(d)

#Secara keseluruhan, program ini adalah untuk menemukan nilai minimal matrix pada kolom tertentu
#dengan axis = 1 menujukan 'kolom' data array

[1 5 9]


In [141]:
e = np.max(a)
print(e)

#Nilai terbesar(masimum) dari array a adalah 12 sehingga hasilnya adalah 12

12


In [143]:
f = np.max(a,axis=0)
print(f)

#Secara keseluruhan, fungsi program ini adalah untuk menemukan nilai maksimum dari baris tertentu
#dengan axis = 0 menujukan 'baris' data array

[ 9 10 11 12]


In [145]:
g = np.max(a,axis=1)
print(g)

#Secara keseluruhan fungsi program ini adalah untuk menemukan nilai maksimum pada kolom tertentu
#dengan axis = 1 menujukan 'kolom' data array

[ 4  8 12]


In [147]:
h = np.sum(a)
print(h)

#Fungsi sum adalah untuk menjumlahkan semua elemen yang ada pada array a
#Total keseluruhan elemennya adalah 78, sehingga hasilnya adalah 78

78


In [149]:
h = np.sum(a,axis=0)
print(h)

#Secara keseluruhan, program ini adalah untuk menjumlahkan semua elemen matrix pada baris tertentu
#dengan axis = 0 menunjukan 'baris' data array

[15 18 21 24]


In [150]:
i = np.sum(a,axis=1)
print(i)

#Secara keseluruhan, program ini adalah untuk menjumlahkan semua elemen matrix pada kolom tertentu
#Dengan axis = 1 menunjukan 'kolom' data array

[10 26 42]
